package amalgam.examples;

import kodkod.ast.*;
import kodkod.ast.SubstituteVisitor;
import kodkod.ast.operator.FormulaOperator;
import kodkod.instance.*;

import java.util.*;

public class RoomHeat implements KodkodExample {

    Relation x0 = Relation.unary("Int/min");
    Relation x1 = Relation.unary("Int/zero");
    Relation x2 = Relation.unary("Int/max");
    Relation x3 = Relation.nary("Int/next", 2);
    Relation x4 = Relation.unary("seq/Int");
    Relation x5 = Relation.unary("String");
    Relation x6 = Relation.unary("this/Config");
    Relation x7 = Relation.unary("this/Time");
    Relation x8 = Relation.unary("ordering/Ord");
    Relation x9 = Relation.unary("boolean/True");
    Relation x10 = Relation.unary("boolean/False");
    Relation x11 = Relation.unary("this/Config.T");
    Relation x12 = Relation.unary("this/Config.F");
    Relation x13 = Relation.unary("this/Config.G");
    Relation x14 = Relation.nary("this/Time.temp", 2);
    Relation x15 = Relation.nary("this/Time.heat", 2);
    Relation x16 = Relation.unary("ordering/Ord.First");
    Relation x17 = Relation.nary("ordering/Ord.Next", 2);
    Relation x18 = Relation.unary("");
    Formula x66;
    Formula x121; Variable x120;
    Formula x196; Variable x195;

    List<String> atomlist = Arrays.asList(
            "-1", "-10", "-100", "-101", "-102",
            "-103", "-104", "-105", "-106", "-107", "-108",
            "-109", "-11", "-110", "-111", "-112", "-113",
            "-114", "-115", "-116", "-117", "-118", "-119",
            "-12", "-120", "-121", "-122", "-123", "-124",
            "-125", "-126", "-127", "-128", "-13", "-14",
            "-15", "-16", "-17", "-18", "-19", "-2",
            "-20", "-21", "-22", "-23", "-24", "-25",
            "-26", "-27", "-28", "-29", "-3", "-30",
            "-31", "-32", "-33", "-34", "-35", "-36",
            "-37", "-38", "-39", "-4", "-40", "-41",
            "-42", "-43", "-44", "-45", "-46", "-47",
            "-48", "-49", "-5", "-50", "-51", "-52",
            "-53", "-54", "-55", "-56", "-57", "-58",
            "-59", "-6", "-60", "-61", "-62", "-63",
            "-64", "-65", "-66", "-67", "-68", "-69",
            "-7", "-70", "-71", "-72", "-73", "-74",
            "-75", "-76", "-77", "-78", "-79", "-8",
            "-80", "-81", "-82", "-83", "-84", "-85",
            "-86", "-87", "-88", "-89", "-9", "-90",
            "-91", "-92", "-93", "-94", "-95", "-96",
            "-97", "-98", "-99", "0", "1", "10",
            "100", "101", "102", "103", "104", "105",
            "106", "107", "108", "109", "11", "110",
            "111", "112", "113", "114", "115", "116",
            "117", "118", "119", "12", "120", "121",
            "122", "123", "124", "125", "126", "127",
            "13", "14", "15", "16", "17", "18",
            "19", "2", "20", "21", "22", "23",
            "24", "25", "26", "27", "28", "29",
            "3", "30", "31", "32", "33", "34",
            "35", "36", "37", "38", "39", "4",
            "40", "41", "42", "43", "44", "45",
            "46", "47", "48", "49", "5", "50",
            "51", "52", "53", "54", "55", "56",
            "57", "58", "59", "6", "60", "61",
            "62", "63", "64", "65", "66", "67",
            "68", "69", "7", "70", "71", "72",
            "73", "74", "75", "76", "77", "78",
            "79", "8", "80", "81", "82", "83",
            "84", "85", "86", "87", "88", "89",
            "9", "90", "91", "92", "93", "94",
            "95", "96", "97", "98", "99", "Config$0",
            "Time$0", "Time$1", "Time$10", "Time$2", "Time$3", "Time$4",
            "Time$5", "Time$6", "Time$7", "Time$8", "Time$9", "boolean/False$0",
            "boolean/True$0", "ordering/Ord$0"
    );
    Universe universe = new Universe(atomlist);
    TupleFactory factory = universe.factory();
    Bounds bounds = new Bounds(universe);
    public RoomHeat() {}
    private TupleSet x3u() {
        TupleSet x3_upper = factory.noneOf(2);
        x3_upper.add(factory.tuple("-128").product(factory.tuple("-127")));
        x3_upper.add(factory.tuple("-127").product(factory.tuple("-126")));
        x3_upper.add(factory.tuple("-126").product(factory.tuple("-125")));
        x3_upper.add(factory.tuple("-125").product(factory.tuple("-124")));
        x3_upper.add(factory.tuple("-124").product(factory.tuple("-123")));
        x3_upper.add(factory.tuple("-123").product(factory.tuple("-122")));
        x3_upper.add(factory.tuple("-122").product(factory.tuple("-121")));
        x3_upper.add(factory.tuple("-121").product(factory.tuple("-120")));
        x3_upper.add(factory.tuple("-120").product(factory.tuple("-119")));
        x3_upper.add(factory.tuple("-119").product(factory.tuple("-118")));
        x3_upper.add(factory.tuple("-118").product(factory.tuple("-117")));
        x3_upper.add(factory.tuple("-117").product(factory.tuple("-116")));
        x3_upper.add(factory.tuple("-116").product(factory.tuple("-115")));
        x3_upper.add(factory.tuple("-115").product(factory.tuple("-114")));
        x3_upper.add(factory.tuple("-114").product(factory.tuple("-113")));
        x3_upper.add(factory.tuple("-113").product(factory.tuple("-112")));
        x3_upper.add(factory.tuple("-112").product(factory.tuple("-111")));
        x3_upper.add(factory.tuple("-111").product(factory.tuple("-110")));
        x3_upper.add(factory.tuple("-110").product(factory.tuple("-109")));
        x3_upper.add(factory.tuple("-109").product(factory.tuple("-108")));
        x3_upper.add(factory.tuple("-108").product(factory.tuple("-107")));
        x3_upper.add(factory.tuple("-107").product(factory.tuple("-106")));
        x3_upper.add(factory.tuple("-106").product(factory.tuple("-105")));
        x3_upper.add(factory.tuple("-105").product(factory.tuple("-104")));
        x3_upper.add(factory.tuple("-104").product(factory.tuple("-103")));
        x3_upper.add(factory.tuple("-103").product(factory.tuple("-102")));
        x3_upper.add(factory.tuple("-102").product(factory.tuple("-101")));
        x3_upper.add(factory.tuple("-101").product(factory.tuple("-100")));
        x3_upper.add(factory.tuple("-100").product(factory.tuple("-99")));
        x3_upper.add(factory.tuple("-99").product(factory.tuple("-98")));
        x3_upper.add(factory.tuple("-98").product(factory.tuple("-97")));
        x3_upper.add(factory.tuple("-97").product(factory.tuple("-96")));
        x3_upper.add(factory.tuple("-96").product(factory.tuple("-95")));
        x3_upper.add(factory.tuple("-95").product(factory.tuple("-94")));
        x3_upper.add(factory.tuple("-94").product(factory.tuple("-93")));
        x3_upper.add(factory.tuple("-93").product(factory.tuple("-92")));
        x3_upper.add(factory.tuple("-92").product(factory.tuple("-91")));
        x3_upper.add(factory.tuple("-91").product(factory.tuple("-90")));
        x3_upper.add(factory.tuple("-90").product(factory.tuple("-89")));
        x3_upper.add(factory.tuple("-89").product(factory.tuple("-88")));
        x3_upper.add(factory.tuple("-88").product(factory.tuple("-87")));
        x3_upper.add(factory.tuple("-87").product(factory.tuple("-86")));
        x3_upper.add(factory.tuple("-86").product(factory.tuple("-85")));
        x3_upper.add(factory.tuple("-85").product(factory.tuple("-84")));
        x3_upper.add(factory.tuple("-84").product(factory.tuple("-83")));
        x3_upper.add(factory.tuple("-83").product(factory.tuple("-82")));
        x3_upper.add(factory.tuple("-82").product(factory.tuple("-81")));
        x3_upper.add(factory.tuple("-81").product(factory.tuple("-80")));
        x3_upper.add(factory.tuple("-80").product(factory.tuple("-79")));
        x3_upper.add(factory.tuple("-79").product(factory.tuple("-78")));
        x3_upper.add(factory.tuple("-78").product(factory.tuple("-77")));
        x3_upper.add(factory.tuple("-77").product(factory.tuple("-76")));
        x3_upper.add(factory.tuple("-76").product(factory.tuple("-75")));
        x3_upper.add(factory.tuple("-75").product(factory.tuple("-74")));
        x3_upper.add(factory.tuple("-74").product(factory.tuple("-73")));
        x3_upper.add(factory.tuple("-73").product(factory.tuple("-72")));
        x3_upper.add(factory.tuple("-72").product(factory.tuple("-71")));
        x3_upper.add(factory.tuple("-71").product(factory.tuple("-70")));
        x3_upper.add(factory.tuple("-70").product(factory.tuple("-69")));
        x3_upper.add(factory.tuple("-69").product(factory.tuple("-68")));
        x3_upper.add(factory.tuple("-68").product(factory.tuple("-67")));
        x3_upper.add(factory.tuple("-67").product(factory.tuple("-66")));
        x3_upper.add(factory.tuple("-66").product(factory.tuple("-65")));
        x3_upper.add(factory.tuple("-65").product(factory.tuple("-64")));
        x3_upper.add(factory.tuple("-64").product(factory.tuple("-63")));
        x3_upper.add(factory.tuple("-63").product(factory.tuple("-62")));
        x3_upper.add(factory.tuple("-62").product(factory.tuple("-61")));
        x3_upper.add(factory.tuple("-61").product(factory.tuple("-60")));
        x3_upper.add(factory.tuple("-60").product(factory.tuple("-59")));
        x3_upper.add(factory.tuple("-59").product(factory.tuple("-58")));
        x3_upper.add(factory.tuple("-58").product(factory.tuple("-57")));
        x3_upper.add(factory.tuple("-57").product(factory.tuple("-56")));
        x3_upper.add(factory.tuple("-56").product(factory.tuple("-55")));
        x3_upper.add(factory.tuple("-55").product(factory.tuple("-54")));
        x3_upper.add(factory.tuple("-54").product(factory.tuple("-53")));
        x3_upper.add(factory.tuple("-53").product(factory.tuple("-52")));
        x3_upper.add(factory.tuple("-52").product(factory.tuple("-51")));
        x3_upper.add(factory.tuple("-51").product(factory.tuple("-50")));
        x3_upper.add(factory.tuple("-50").product(factory.tuple("-49")));
        x3_upper.add(factory.tuple("-49").product(factory.tuple("-48")));
        x3_upper.add(factory.tuple("-48").product(factory.tuple("-47")));
        x3_upper.add(factory.tuple("-47").product(factory.tuple("-46")));
        x3_upper.add(factory.tuple("-46").product(factory.tuple("-45")));
        x3_upper.add(factory.tuple("-45").product(factory.tuple("-44")));
        x3_upper.add(factory.tuple("-44").product(factory.tuple("-43")));
        x3_upper.add(factory.tuple("-43").product(factory.tuple("-42")));
        x3_upper.add(factory.tuple("-42").product(factory.tuple("-41")));
        x3_upper.add(factory.tuple("-41").product(factory.tuple("-40")));
        x3_upper.add(factory.tuple("-40").product(factory.tuple("-39")));
        x3_upper.add(factory.tuple("-39").product(factory.tuple("-38")));
        x3_upper.add(factory.tuple("-38").product(factory.tuple("-37")));
        x3_upper.add(factory.tuple("-37").product(factory.tuple("-36")));
        x3_upper.add(factory.tuple("-36").product(factory.tuple("-35")));
        x3_upper.add(factory.tuple("-35").product(factory.tuple("-34")));
        x3_upper.add(factory.tuple("-34").product(factory.tuple("-33")));
        x3_upper.add(factory.tuple("-33").product(factory.tuple("-32")));
        x3_upper.add(factory.tuple("-32").product(factory.tuple("-31")));
        x3_upper.add(factory.tuple("-31").product(factory.tuple("-30")));
        x3_upper.add(factory.tuple("-30").product(factory.tuple("-29")));
        x3_upper.add(factory.tuple("-29").product(factory.tuple("-28")));
        x3_upper.add(factory.tuple("-28").product(factory.tuple("-27")));
        x3_upper.add(factory.tuple("-27").product(factory.tuple("-26")));
        x3_upper.add(factory.tuple("-26").product(factory.tuple("-25")));
        x3_upper.add(factory.tuple("-25").product(factory.tuple("-24")));
        x3_upper.add(factory.tuple("-24").product(factory.tuple("-23")));
        x3_upper.add(factory.tuple("-23").product(factory.tuple("-22")));
        x3_upper.add(factory.tuple("-22").product(factory.tuple("-21")));
        x3_upper.add(factory.tuple("-21").product(factory.tuple("-20")));
        x3_upper.add(factory.tuple("-20").product(factory.tuple("-19")));
        x3_upper.add(factory.tuple("-19").product(factory.tuple("-18")));
        x3_upper.add(factory.tuple("-18").product(factory.tuple("-17")));
        x3_upper.add(factory.tuple("-17").product(factory.tuple("-16")));
        x3_upper.add(factory.tuple("-16").product(factory.tuple("-15")));
        x3_upper.add(factory.tuple("-15").product(factory.tuple("-14")));
        x3_upper.add(factory.tuple("-14").product(factory.tuple("-13")));
        x3_upper.add(factory.tuple("-13").product(factory.tuple("-12")));
        x3_upper.add(factory.tuple("-12").product(factory.tuple("-11")));
        x3_upper.add(factory.tuple("-11").product(factory.tuple("-10")));
        x3_upper.add(factory.tuple("-10").product(factory.tuple("-9")));
        x3_upper.add(factory.tuple("-9").product(factory.tuple("-8")));
        x3_upper.add(factory.tuple("-8").product(factory.tuple("-7")));
        x3_upper.add(factory.tuple("-7").product(factory.tuple("-6")));
        x3_upper.add(factory.tuple("-6").product(factory.tuple("-5")));
        x3_upper.add(factory.tuple("-5").product(factory.tuple("-4")));
        x3_upper.add(factory.tuple("-4").product(factory.tuple("-3")));
        x3_upper.add(factory.tuple("-3").product(factory.tuple("-2")));
        x3_upper.add(factory.tuple("-2").product(factory.tuple("-1")));
        x3_upper.add(factory.tuple("-1").product(factory.tuple("0")));
        x3_upper.add(factory.tuple("0").product(factory.tuple("1")));
        x3_upper.add(factory.tuple("1").product(factory.tuple("2")));
        x3_upper.add(factory.tuple("2").product(factory.tuple("3")));
        x3_upper.add(factory.tuple("3").product(factory.tuple("4")));
        x3_upper.add(factory.tuple("4").product(factory.tuple("5")));
        x3_upper.add(factory.tuple("5").product(factory.tuple("6")));
        x3_upper.add(factory.tuple("6").product(factory.tuple("7")));
        x3_upper.add(factory.tuple("7").product(factory.tuple("8")));
        x3_upper.add(factory.tuple("8").product(factory.tuple("9")));
        x3_upper.add(factory.tuple("9").product(factory.tuple("10")));
        x3_upper.add(factory.tuple("10").product(factory.tuple("11")));
        x3_upper.add(factory.tuple("11").product(factory.tuple("12")));
        x3_upper.add(factory.tuple("12").product(factory.tuple("13")));
        x3_upper.add(factory.tuple("13").product(factory.tuple("14")));
        x3_upper.add(factory.tuple("14").product(factory.tuple("15")));
        x3_upper.add(factory.tuple("15").product(factory.tuple("16")));
        x3_upper.add(factory.tuple("16").product(factory.tuple("17")));
        x3_upper.add(factory.tuple("17").product(factory.tuple("18")));
        x3_upper.add(factory.tuple("18").product(factory.tuple("19")));
        x3_upper.add(factory.tuple("19").product(factory.tuple("20")));
        x3_upper.add(factory.tuple("20").product(factory.tuple("21")));
        x3_upper.add(factory.tuple("21").product(factory.tuple("22")));
        x3_upper.add(factory.tuple("22").product(factory.tuple("23")));
        x3_upper.add(factory.tuple("23").product(factory.tuple("24")));
        x3_upper.add(factory.tuple("24").product(factory.tuple("25")));
        x3_upper.add(factory.tuple("25").product(factory.tuple("26")));
        x3_upper.add(factory.tuple("26").product(factory.tuple("27")));
        x3_upper.add(factory.tuple("27").product(factory.tuple("28")));
        x3_upper.add(factory.tuple("28").product(factory.tuple("29")));
        x3_upper.add(factory.tuple("29").product(factory.tuple("30")));
        x3_upper.add(factory.tuple("30").product(factory.tuple("31")));
        x3_upper.add(factory.tuple("31").product(factory.tuple("32")));
        x3_upper.add(factory.tuple("32").product(factory.tuple("33")));
        x3_upper.add(factory.tuple("33").product(factory.tuple("34")));
        x3_upper.add(factory.tuple("34").product(factory.tuple("35")));
        x3_upper.add(factory.tuple("35").product(factory.tuple("36")));
        x3_upper.add(factory.tuple("36").product(factory.tuple("37")));
        x3_upper.add(factory.tuple("37").product(factory.tuple("38")));
        x3_upper.add(factory.tuple("38").product(factory.tuple("39")));
        x3_upper.add(factory.tuple("39").product(factory.tuple("40")));
        x3_upper.add(factory.tuple("40").product(factory.tuple("41")));
        x3_upper.add(factory.tuple("41").product(factory.tuple("42")));
        x3_upper.add(factory.tuple("42").product(factory.tuple("43")));
        x3_upper.add(factory.tuple("43").product(factory.tuple("44")));
        x3_upper.add(factory.tuple("44").product(factory.tuple("45")));
        x3_upper.add(factory.tuple("45").product(factory.tuple("46")));
        x3_upper.add(factory.tuple("46").product(factory.tuple("47")));
        x3_upper.add(factory.tuple("47").product(factory.tuple("48")));
        x3_upper.add(factory.tuple("48").product(factory.tuple("49")));
        x3_upper.add(factory.tuple("49").product(factory.tuple("50")));
        x3_upper.add(factory.tuple("50").product(factory.tuple("51")));
        x3_upper.add(factory.tuple("51").product(factory.tuple("52")));
        x3_upper.add(factory.tuple("52").product(factory.tuple("53")));
        x3_upper.add(factory.tuple("53").product(factory.tuple("54")));
        x3_upper.add(factory.tuple("54").product(factory.tuple("55")));
        x3_upper.add(factory.tuple("55").product(factory.tuple("56")));
        x3_upper.add(factory.tuple("56").product(factory.tuple("57")));
        x3_upper.add(factory.tuple("57").product(factory.tuple("58")));
        x3_upper.add(factory.tuple("58").product(factory.tuple("59")));
        x3_upper.add(factory.tuple("59").product(factory.tuple("60")));
        x3_upper.add(factory.tuple("60").product(factory.tuple("61")));
        x3_upper.add(factory.tuple("61").product(factory.tuple("62")));
        x3_upper.add(factory.tuple("62").product(factory.tuple("63")));
        x3_upper.add(factory.tuple("63").product(factory.tuple("64")));
        x3_upper.add(factory.tuple("64").product(factory.tuple("65")));
        x3_upper.add(factory.tuple("65").product(factory.tuple("66")));
        x3_upper.add(factory.tuple("66").product(factory.tuple("67")));
        x3_upper.add(factory.tuple("67").product(factory.tuple("68")));
        x3_upper.add(factory.tuple("68").product(factory.tuple("69")));
        x3_upper.add(factory.tuple("69").product(factory.tuple("70")));
        x3_upper.add(factory.tuple("70").product(factory.tuple("71")));
        x3_upper.add(factory.tuple("71").product(factory.tuple("72")));
        x3_upper.add(factory.tuple("72").product(factory.tuple("73")));
        x3_upper.add(factory.tuple("73").product(factory.tuple("74")));
        x3_upper.add(factory.tuple("74").product(factory.tuple("75")));
        x3_upper.add(factory.tuple("75").product(factory.tuple("76")));
        x3_upper.add(factory.tuple("76").product(factory.tuple("77")));
        x3_upper.add(factory.tuple("77").product(factory.tuple("78")));
        x3_upper.add(factory.tuple("78").product(factory.tuple("79")));
        x3_upper.add(factory.tuple("79").product(factory.tuple("80")));
        x3_upper.add(factory.tuple("80").product(factory.tuple("81")));
        x3_upper.add(factory.tuple("81").product(factory.tuple("82")));
        x3_upper.add(factory.tuple("82").product(factory.tuple("83")));
        x3_upper.add(factory.tuple("83").product(factory.tuple("84")));
        x3_upper.add(factory.tuple("84").product(factory.tuple("85")));
        x3_upper.add(factory.tuple("85").product(factory.tuple("86")));
        x3_upper.add(factory.tuple("86").product(factory.tuple("87")));
        x3_upper.add(factory.tuple("87").product(factory.tuple("88")));
        x3_upper.add(factory.tuple("88").product(factory.tuple("89")));
        x3_upper.add(factory.tuple("89").product(factory.tuple("90")));
        x3_upper.add(factory.tuple("90").product(factory.tuple("91")));
        x3_upper.add(factory.tuple("91").product(factory.tuple("92")));
        x3_upper.add(factory.tuple("92").product(factory.tuple("93")));
        x3_upper.add(factory.tuple("93").product(factory.tuple("94")));
        x3_upper.add(factory.tuple("94").product(factory.tuple("95")));
        x3_upper.add(factory.tuple("95").product(factory.tuple("96")));
        x3_upper.add(factory.tuple("96").product(factory.tuple("97")));
        x3_upper.add(factory.tuple("97").product(factory.tuple("98")));
        x3_upper.add(factory.tuple("98").product(factory.tuple("99")));
        x3_upper.add(factory.tuple("99").product(factory.tuple("100")));
        x3_upper.add(factory.tuple("100").product(factory.tuple("101")));
        x3_upper.add(factory.tuple("101").product(factory.tuple("102")));
        x3_upper.add(factory.tuple("102").product(factory.tuple("103")));
        x3_upper.add(factory.tuple("103").product(factory.tuple("104")));
        x3_upper.add(factory.tuple("104").product(factory.tuple("105")));
        x3_upper.add(factory.tuple("105").product(factory.tuple("106")));
        x3_upper.add(factory.tuple("106").product(factory.tuple("107")));
        x3_upper.add(factory.tuple("107").product(factory.tuple("108")));
        x3_upper.add(factory.tuple("108").product(factory.tuple("109")));
        x3_upper.add(factory.tuple("109").product(factory.tuple("110")));
        x3_upper.add(factory.tuple("110").product(factory.tuple("111")));
        x3_upper.add(factory.tuple("111").product(factory.tuple("112")));
        x3_upper.add(factory.tuple("112").product(factory.tuple("113")));
        x3_upper.add(factory.tuple("113").product(factory.tuple("114")));
        x3_upper.add(factory.tuple("114").product(factory.tuple("115")));
        x3_upper.add(factory.tuple("115").product(factory.tuple("116")));
        x3_upper.add(factory.tuple("116").product(factory.tuple("117")));
        x3_upper.add(factory.tuple("117").product(factory.tuple("118")));
        x3_upper.add(factory.tuple("118").product(factory.tuple("119")));
        x3_upper.add(factory.tuple("119").product(factory.tuple("120")));
        x3_upper.add(factory.tuple("120").product(factory.tuple("121")));
        x3_upper.add(factory.tuple("121").product(factory.tuple("122")));
        x3_upper.add(factory.tuple("122").product(factory.tuple("123")));
        x3_upper.add(factory.tuple("123").product(factory.tuple("124")));
        x3_upper.add(factory.tuple("124").product(factory.tuple("125")));
        x3_upper.add(factory.tuple("125").product(factory.tuple("126")));
        x3_upper.add(factory.tuple("126").product(factory.tuple("127")));
        return x3_upper;
    }
    private TupleSet x11u() {
        TupleSet x11_upper = factory.noneOf(1);
        x11_upper.add(factory.tuple("-128"));
        x11_upper.add(factory.tuple("-127"));
        x11_upper.add(factory.tuple("-126"));
        x11_upper.add(factory.tuple("-125"));
        x11_upper.add(factory.tuple("-124"));
        x11_upper.add(factory.tuple("-123"));
        x11_upper.add(factory.tuple("-122"));
        x11_upper.add(factory.tuple("-121"));
        x11_upper.add(factory.tuple("-120"));
        x11_upper.add(factory.tuple("-119"));
        x11_upper.add(factory.tuple("-118"));
        x11_upper.add(factory.tuple("-117"));
        x11_upper.add(factory.tuple("-116"));
        x11_upper.add(factory.tuple("-115"));
        x11_upper.add(factory.tuple("-114"));
        x11_upper.add(factory.tuple("-113"));
        x11_upper.add(factory.tuple("-112"));
        x11_upper.add(factory.tuple("-111"));
        x11_upper.add(factory.tuple("-110"));
        x11_upper.add(factory.tuple("-109"));
        x11_upper.add(factory.tuple("-108"));
        x11_upper.add(factory.tuple("-107"));
        x11_upper.add(factory.tuple("-106"));
        x11_upper.add(factory.tuple("-105"));
        x11_upper.add(factory.tuple("-104"));
        x11_upper.add(factory.tuple("-103"));
        x11_upper.add(factory.tuple("-102"));
        x11_upper.add(factory.tuple("-101"));
        x11_upper.add(factory.tuple("-100"));
        x11_upper.add(factory.tuple("-99"));
        x11_upper.add(factory.tuple("-98"));
        x11_upper.add(factory.tuple("-97"));
        x11_upper.add(factory.tuple("-96"));
        x11_upper.add(factory.tuple("-95"));
        x11_upper.add(factory.tuple("-94"));
        x11_upper.add(factory.tuple("-93"));
        x11_upper.add(factory.tuple("-92"));
        x11_upper.add(factory.tuple("-91"));
        x11_upper.add(factory.tuple("-90"));
        x11_upper.add(factory.tuple("-89"));
        x11_upper.add(factory.tuple("-88"));
        x11_upper.add(factory.tuple("-87"));
        x11_upper.add(factory.tuple("-86"));
        x11_upper.add(factory.tuple("-85"));
        x11_upper.add(factory.tuple("-84"));
        x11_upper.add(factory.tuple("-83"));
        x11_upper.add(factory.tuple("-82"));
        x11_upper.add(factory.tuple("-81"));
        x11_upper.add(factory.tuple("-80"));
        x11_upper.add(factory.tuple("-79"));
        x11_upper.add(factory.tuple("-78"));
        x11_upper.add(factory.tuple("-77"));
        x11_upper.add(factory.tuple("-76"));
        x11_upper.add(factory.tuple("-75"));
        x11_upper.add(factory.tuple("-74"));
        x11_upper.add(factory.tuple("-73"));
        x11_upper.add(factory.tuple("-72"));
        x11_upper.add(factory.tuple("-71"));
        x11_upper.add(factory.tuple("-70"));
        x11_upper.add(factory.tuple("-69"));
        x11_upper.add(factory.tuple("-68"));
        x11_upper.add(factory.tuple("-67"));
        x11_upper.add(factory.tuple("-66"));
        x11_upper.add(factory.tuple("-65"));
        x11_upper.add(factory.tuple("-64"));
        x11_upper.add(factory.tuple("-63"));
        x11_upper.add(factory.tuple("-62"));
        x11_upper.add(factory.tuple("-61"));
        x11_upper.add(factory.tuple("-60"));
        x11_upper.add(factory.tuple("-59"));
        x11_upper.add(factory.tuple("-58"));
        x11_upper.add(factory.tuple("-57"));
        x11_upper.add(factory.tuple("-56"));
        x11_upper.add(factory.tuple("-55"));
        x11_upper.add(factory.tuple("-54"));
        x11_upper.add(factory.tuple("-53"));
        x11_upper.add(factory.tuple("-52"));
        x11_upper.add(factory.tuple("-51"));
        x11_upper.add(factory.tuple("-50"));
        x11_upper.add(factory.tuple("-49"));
        x11_upper.add(factory.tuple("-48"));
        x11_upper.add(factory.tuple("-47"));
        x11_upper.add(factory.tuple("-46"));
        x11_upper.add(factory.tuple("-45"));
        x11_upper.add(factory.tuple("-44"));
        x11_upper.add(factory.tuple("-43"));
        x11_upper.add(factory.tuple("-42"));
        x11_upper.add(factory.tuple("-41"));
        x11_upper.add(factory.tuple("-40"));
        x11_upper.add(factory.tuple("-39"));
        x11_upper.add(factory.tuple("-38"));
        x11_upper.add(factory.tuple("-37"));
        x11_upper.add(factory.tuple("-36"));
        x11_upper.add(factory.tuple("-35"));
        x11_upper.add(factory.tuple("-34"));
        x11_upper.add(factory.tuple("-33"));
        x11_upper.add(factory.tuple("-32"));
        x11_upper.add(factory.tuple("-31"));
        x11_upper.add(factory.tuple("-30"));
        x11_upper.add(factory.tuple("-29"));
        x11_upper.add(factory.tuple("-28"));
        x11_upper.add(factory.tuple("-27"));
        x11_upper.add(factory.tuple("-26"));
        x11_upper.add(factory.tuple("-25"));
        x11_upper.add(factory.tuple("-24"));
        x11_upper.add(factory.tuple("-23"));
        x11_upper.add(factory.tuple("-22"));
        x11_upper.add(factory.tuple("-21"));
        x11_upper.add(factory.tuple("-20"));
        x11_upper.add(factory.tuple("-19"));
        x11_upper.add(factory.tuple("-18"));
        x11_upper.add(factory.tuple("-17"));
        x11_upper.add(factory.tuple("-16"));
        x11_upper.add(factory.tuple("-15"));
        x11_upper.add(factory.tuple("-14"));
        x11_upper.add(factory.tuple("-13"));
        x11_upper.add(factory.tuple("-12"));
        x11_upper.add(factory.tuple("-11"));
        x11_upper.add(factory.tuple("-10"));
        x11_upper.add(factory.tuple("-9"));
        x11_upper.add(factory.tuple("-8"));
        x11_upper.add(factory.tuple("-7"));
        x11_upper.add(factory.tuple("-6"));
        x11_upper.add(factory.tuple("-5"));
        x11_upper.add(factory.tuple("-4"));
        x11_upper.add(factory.tuple("-3"));
        x11_upper.add(factory.tuple("-2"));
        x11_upper.add(factory.tuple("-1"));
        x11_upper.add(factory.tuple("0"));
        x11_upper.add(factory.tuple("1"));
        x11_upper.add(factory.tuple("2"));
        x11_upper.add(factory.tuple("3"));
        x11_upper.add(factory.tuple("4"));
        x11_upper.add(factory.tuple("5"));
        x11_upper.add(factory.tuple("6"));
        x11_upper.add(factory.tuple("7"));
        x11_upper.add(factory.tuple("8"));
        x11_upper.add(factory.tuple("9"));
        x11_upper.add(factory.tuple("10"));
        x11_upper.add(factory.tuple("11"));
        x11_upper.add(factory.tuple("12"));
        x11_upper.add(factory.tuple("13"));
        x11_upper.add(factory.tuple("14"));
        x11_upper.add(factory.tuple("15"));
        x11_upper.add(factory.tuple("16"));
        x11_upper.add(factory.tuple("17"));
        x11_upper.add(factory.tuple("18"));
        x11_upper.add(factory.tuple("19"));
        x11_upper.add(factory.tuple("20"));
        x11_upper.add(factory.tuple("21"));
        x11_upper.add(factory.tuple("22"));
        x11_upper.add(factory.tuple("23"));
        x11_upper.add(factory.tuple("24"));
        x11_upper.add(factory.tuple("25"));
        x11_upper.add(factory.tuple("26"));
        x11_upper.add(factory.tuple("27"));
        x11_upper.add(factory.tuple("28"));
        x11_upper.add(factory.tuple("29"));
        x11_upper.add(factory.tuple("30"));
        x11_upper.add(factory.tuple("31"));
        x11_upper.add(factory.tuple("32"));
        x11_upper.add(factory.tuple("33"));
        x11_upper.add(factory.tuple("34"));
        x11_upper.add(factory.tuple("35"));
        x11_upper.add(factory.tuple("36"));
        x11_upper.add(factory.tuple("37"));
        x11_upper.add(factory.tuple("38"));
        x11_upper.add(factory.tuple("39"));
        x11_upper.add(factory.tuple("40"));
        x11_upper.add(factory.tuple("41"));
        x11_upper.add(factory.tuple("42"));
        x11_upper.add(factory.tuple("43"));
        x11_upper.add(factory.tuple("44"));
        x11_upper.add(factory.tuple("45"));
        x11_upper.add(factory.tuple("46"));
        x11_upper.add(factory.tuple("47"));
        x11_upper.add(factory.tuple("48"));
        x11_upper.add(factory.tuple("49"));
        x11_upper.add(factory.tuple("50"));
        x11_upper.add(factory.tuple("51"));
        x11_upper.add(factory.tuple("52"));
        x11_upper.add(factory.tuple("53"));
        x11_upper.add(factory.tuple("54"));
        x11_upper.add(factory.tuple("55"));
        x11_upper.add(factory.tuple("56"));
        x11_upper.add(factory.tuple("57"));
        x11_upper.add(factory.tuple("58"));
        x11_upper.add(factory.tuple("59"));
        x11_upper.add(factory.tuple("60"));
        x11_upper.add(factory.tuple("61"));
        x11_upper.add(factory.tuple("62"));
        x11_upper.add(factory.tuple("63"));
        x11_upper.add(factory.tuple("64"));
        x11_upper.add(factory.tuple("65"));
        x11_upper.add(factory.tuple("66"));
        x11_upper.add(factory.tuple("67"));
        x11_upper.add(factory.tuple("68"));
        x11_upper.add(factory.tuple("69"));
        x11_upper.add(factory.tuple("70"));
        x11_upper.add(factory.tuple("71"));
        x11_upper.add(factory.tuple("72"));
        x11_upper.add(factory.tuple("73"));
        x11_upper.add(factory.tuple("74"));
        x11_upper.add(factory.tuple("75"));
        x11_upper.add(factory.tuple("76"));
        x11_upper.add(factory.tuple("77"));
        x11_upper.add(factory.tuple("78"));
        x11_upper.add(factory.tuple("79"));
        x11_upper.add(factory.tuple("80"));
        x11_upper.add(factory.tuple("81"));
        x11_upper.add(factory.tuple("82"));
        x11_upper.add(factory.tuple("83"));
        x11_upper.add(factory.tuple("84"));
        x11_upper.add(factory.tuple("85"));
        x11_upper.add(factory.tuple("86"));
        x11_upper.add(factory.tuple("87"));
        x11_upper.add(factory.tuple("88"));
        x11_upper.add(factory.tuple("89"));
        x11_upper.add(factory.tuple("90"));
        x11_upper.add(factory.tuple("91"));
        x11_upper.add(factory.tuple("92"));
        x11_upper.add(factory.tuple("93"));
        x11_upper.add(factory.tuple("94"));
        x11_upper.add(factory.tuple("95"));
        x11_upper.add(factory.tuple("96"));
        x11_upper.add(factory.tuple("97"));
        x11_upper.add(factory.tuple("98"));
        x11_upper.add(factory.tuple("99"));
        x11_upper.add(factory.tuple("100"));
        x11_upper.add(factory.tuple("101"));
        x11_upper.add(factory.tuple("102"));
        x11_upper.add(factory.tuple("103"));
        x11_upper.add(factory.tuple("104"));
        x11_upper.add(factory.tuple("105"));
        x11_upper.add(factory.tuple("106"));
        x11_upper.add(factory.tuple("107"));
        x11_upper.add(factory.tuple("108"));
        x11_upper.add(factory.tuple("109"));
        x11_upper.add(factory.tuple("110"));
        x11_upper.add(factory.tuple("111"));
        x11_upper.add(factory.tuple("112"));
        x11_upper.add(factory.tuple("113"));
        x11_upper.add(factory.tuple("114"));
        x11_upper.add(factory.tuple("115"));
        x11_upper.add(factory.tuple("116"));
        x11_upper.add(factory.tuple("117"));
        x11_upper.add(factory.tuple("118"));
        x11_upper.add(factory.tuple("119"));
        x11_upper.add(factory.tuple("120"));
        x11_upper.add(factory.tuple("121"));
        x11_upper.add(factory.tuple("122"));
        x11_upper.add(factory.tuple("123"));
        x11_upper.add(factory.tuple("124"));
        x11_upper.add(factory.tuple("125"));
        x11_upper.add(factory.tuple("126"));
        x11_upper.add(factory.tuple("127"));
        return x11_upper;
    }
    private TupleSet x14u() {
        TupleSet x14_upper = factory.noneOf(2);
        for(int i=0; i<=10; i++) {
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-128")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-127")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-126")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-125")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-124")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-123")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-122")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-121")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-120")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-119")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-118")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-117")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-116")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-115")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-114")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-113")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-112")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-111")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-110")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-109")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-108")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-107")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-106")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-105")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-104")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-103")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-102")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-101")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-100")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-99")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-98")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-97")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-96")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-95")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-94")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-93")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-92")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-91")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-90")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-89")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-88")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-87")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-86")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-85")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-84")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-83")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-82")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-81")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-80")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-79")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-78")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-77")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-76")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-75")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-74")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-73")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-72")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-71")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-70")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-69")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-68")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-67")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-66")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-65")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-64")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-63")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-62")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-61")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-60")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-59")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-58")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-57")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-56")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-55")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-54")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-53")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-52")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-51")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-50")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-49")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-48")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-47")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-46")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-45")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-44")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-43")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-42")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-41")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-40")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-39")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-38")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-37")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-36")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-35")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-34")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-33")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-32")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-31")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-30")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-29")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-28")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-27")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-26")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-25")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-24")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-23")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-22")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-21")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-20")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-19")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-18")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-17")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-16")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-15")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-14")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-13")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-12")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-11")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-10")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-9")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-8")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-7")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-6")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-5")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-4")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-3")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-2")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("-1")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("0")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("1")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("2")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("3")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("4")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("5")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("6")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("7")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("8")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("9")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("10")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("11")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("12")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("13")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("14")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("15")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("16")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("17")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("18")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("19")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("20")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("21")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("22")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("23")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("24")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("25")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("26")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("27")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("28")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("29")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("30")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("31")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("32")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("33")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("34")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("35")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("36")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("37")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("38")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("39")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("40")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("41")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("42")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("43")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("44")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("45")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("46")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("47")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("48")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("49")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("50")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("51")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("52")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("53")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("54")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("55")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("56")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("57")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("58")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("59")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("60")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("61")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("62")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("63")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("64")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("65")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("66")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("67")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("68")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("69")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("70")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("71")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("72")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("73")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("74")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("75")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("76")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("77")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("78")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("79")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("80")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("81")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("82")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("83")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("84")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("85")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("86")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("87")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("88")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("89")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("90")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("91")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("92")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("93")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("94")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("95")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("96")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("97")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("98")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("99")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("100")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("101")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("102")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("103")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("104")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("105")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("106")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("107")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("108")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("109")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("110")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("111")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("112")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("113")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("114")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("115")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("116")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("117")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("118")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("119")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("120")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("121")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("122")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("123")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("124")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("125")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("126")));
            x14_upper.add(factory.tuple("Time$"+i).product(factory.tuple("127")));
        }
        return x14_upper;
    }
    @Override
    public Bounds bounds(int n) {

        TupleSet x0_upper = factory.noneOf(1);
        x0_upper.add(factory.tuple("-128"));
        bounds.boundExactly(x0, x0_upper);

        TupleSet x1_upper = factory.noneOf(1);
        x1_upper.add(factory.tuple("0"));
        bounds.boundExactly(x1, x1_upper);

        TupleSet x2_upper = factory.noneOf(1);
        x2_upper.add(factory.tuple("127"));
        bounds.boundExactly(x2, x2_upper);

        bounds.boundExactly(x3, x3u());

        TupleSet x4_upper = factory.noneOf(1);
        x4_upper.add(factory.tuple("0"));
        x4_upper.add(factory.tuple("1"));
        x4_upper.add(factory.tuple("2"));
        x4_upper.add(factory.tuple("3"));
        bounds.boundExactly(x4, x4_upper);

        TupleSet x5_upper = factory.noneOf(1);
        bounds.boundExactly(x5, x5_upper);

        TupleSet x6_upper = factory.noneOf(1);
        x6_upper.add(factory.tuple("Config$0"));
        bounds.boundExactly(x6, x6_upper);

        TupleSet x7_upper = factory.noneOf(1);
        x7_upper.add(factory.tuple("Time$0"));
        x7_upper.add(factory.tuple("Time$1"));
        x7_upper.add(factory.tuple("Time$2"));
        x7_upper.add(factory.tuple("Time$3"));
        x7_upper.add(factory.tuple("Time$4"));
        x7_upper.add(factory.tuple("Time$5"));
        x7_upper.add(factory.tuple("Time$6"));
        x7_upper.add(factory.tuple("Time$7"));
        x7_upper.add(factory.tuple("Time$8"));
        x7_upper.add(factory.tuple("Time$9"));
        x7_upper.add(factory.tuple("Time$10"));
        bounds.boundExactly(x7, x7_upper);

        TupleSet x8_upper = factory.noneOf(1);
        x8_upper.add(factory.tuple("ordering/Ord$0"));
        bounds.boundExactly(x8, x8_upper);

        TupleSet x9_upper = factory.noneOf(1);
        x9_upper.add(factory.tuple("boolean/True$0"));
        bounds.boundExactly(x9, x9_upper);

        TupleSet x10_upper = factory.noneOf(1);
        x10_upper.add(factory.tuple("boolean/False$0"));
        bounds.boundExactly(x10, x10_upper);

        bounds.bound(x11, x11u());

        TupleSet x12_upper = factory.noneOf(1);
        x12_upper.add(factory.tuple("Time$0"));
        x12_upper.add(factory.tuple("Time$1"));
        x12_upper.add(factory.tuple("Time$2"));
        x12_upper.add(factory.tuple("Time$3"));
        x12_upper.add(factory.tuple("Time$4"));
        x12_upper.add(factory.tuple("Time$5"));
        x12_upper.add(factory.tuple("Time$6"));
        x12_upper.add(factory.tuple("Time$7"));
        x12_upper.add(factory.tuple("Time$8"));
        x12_upper.add(factory.tuple("Time$9"));
        x12_upper.add(factory.tuple("Time$10"));
        bounds.bound(x12, x12_upper);

        TupleSet x13_upper = factory.noneOf(1);
        x13_upper.add(factory.tuple("Time$0"));
        x13_upper.add(factory.tuple("Time$1"));
        x13_upper.add(factory.tuple("Time$2"));
        x13_upper.add(factory.tuple("Time$3"));
        x13_upper.add(factory.tuple("Time$4"));
        x13_upper.add(factory.tuple("Time$5"));
        x13_upper.add(factory.tuple("Time$6"));
        x13_upper.add(factory.tuple("Time$7"));
        x13_upper.add(factory.tuple("Time$8"));
        x13_upper.add(factory.tuple("Time$9"));
        x13_upper.add(factory.tuple("Time$10"));
        bounds.bound(x13, x13_upper);

        bounds.bound(x14, x14u());

        TupleSet x15_upper = factory.noneOf(2);
        x15_upper.add(factory.tuple("Time$0").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$0").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$1").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$1").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$2").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$2").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$3").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$3").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$4").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$4").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$5").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$5").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$6").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$6").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$7").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$7").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$8").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$8").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$9").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$9").product(factory.tuple("boolean/False$0")));
        x15_upper.add(factory.tuple("Time$10").product(factory.tuple("boolean/True$0")));
        x15_upper.add(factory.tuple("Time$10").product(factory.tuple("boolean/False$0")));
        bounds.bound(x15, x15_upper);

        TupleSet x16_upper = factory.noneOf(1);
        x16_upper.add(factory.tuple("Time$0"));
        bounds.boundExactly(x16, x16_upper);

        TupleSet x17_upper = factory.noneOf(2);
        x17_upper.add(factory.tuple("Time$0").product(factory.tuple("Time$1")));
        x17_upper.add(factory.tuple("Time$1").product(factory.tuple("Time$2")));
        x17_upper.add(factory.tuple("Time$2").product(factory.tuple("Time$3")));
        x17_upper.add(factory.tuple("Time$3").product(factory.tuple("Time$4")));
        x17_upper.add(factory.tuple("Time$4").product(factory.tuple("Time$5")));
        x17_upper.add(factory.tuple("Time$5").product(factory.tuple("Time$6")));
        x17_upper.add(factory.tuple("Time$6").product(factory.tuple("Time$7")));
        x17_upper.add(factory.tuple("Time$7").product(factory.tuple("Time$8")));
        x17_upper.add(factory.tuple("Time$8").product(factory.tuple("Time$9")));
        x17_upper.add(factory.tuple("Time$9").product(factory.tuple("Time$10")));
        bounds.boundExactly(x17, x17_upper);

        TupleSet x18_upper = factory.noneOf(1);
        x18_upper.add(factory.tuple("Time$0"));
        x18_upper.add(factory.tuple("Time$1"));
        x18_upper.add(factory.tuple("Time$2"));
        x18_upper.add(factory.tuple("Time$3"));
        x18_upper.add(factory.tuple("Time$4"));
        x18_upper.add(factory.tuple("Time$5"));
        x18_upper.add(factory.tuple("Time$6"));
        x18_upper.add(factory.tuple("Time$7"));
        x18_upper.add(factory.tuple("Time$8"));
        x18_upper.add(factory.tuple("Time$9"));
        x18_upper.add(factory.tuple("Time$10"));
        bounds.bound(x18, x18_upper);

        bounds.boundExactly(-128,factory.range(factory.tuple("-128"),factory.tuple("-128")));
        bounds.boundExactly(-127,factory.range(factory.tuple("-127"),factory.tuple("-127")));
        bounds.boundExactly(-126,factory.range(factory.tuple("-126"),factory.tuple("-126")));
        bounds.boundExactly(-125,factory.range(factory.tuple("-125"),factory.tuple("-125")));
        bounds.boundExactly(-124,factory.range(factory.tuple("-124"),factory.tuple("-124")));
        bounds.boundExactly(-123,factory.range(factory.tuple("-123"),factory.tuple("-123")));
        bounds.boundExactly(-122,factory.range(factory.tuple("-122"),factory.tuple("-122")));
        bounds.boundExactly(-121,factory.range(factory.tuple("-121"),factory.tuple("-121")));
        bounds.boundExactly(-120,factory.range(factory.tuple("-120"),factory.tuple("-120")));
        bounds.boundExactly(-119,factory.range(factory.tuple("-119"),factory.tuple("-119")));
        bounds.boundExactly(-118,factory.range(factory.tuple("-118"),factory.tuple("-118")));
        bounds.boundExactly(-117,factory.range(factory.tuple("-117"),factory.tuple("-117")));
        bounds.boundExactly(-116,factory.range(factory.tuple("-116"),factory.tuple("-116")));
        bounds.boundExactly(-115,factory.range(factory.tuple("-115"),factory.tuple("-115")));
        bounds.boundExactly(-114,factory.range(factory.tuple("-114"),factory.tuple("-114")));
        bounds.boundExactly(-113,factory.range(factory.tuple("-113"),factory.tuple("-113")));
        bounds.boundExactly(-112,factory.range(factory.tuple("-112"),factory.tuple("-112")));
        bounds.boundExactly(-111,factory.range(factory.tuple("-111"),factory.tuple("-111")));
        bounds.boundExactly(-110,factory.range(factory.tuple("-110"),factory.tuple("-110")));
        bounds.boundExactly(-109,factory.range(factory.tuple("-109"),factory.tuple("-109")));
        bounds.boundExactly(-108,factory.range(factory.tuple("-108"),factory.tuple("-108")));
        bounds.boundExactly(-107,factory.range(factory.tuple("-107"),factory.tuple("-107")));
        bounds.boundExactly(-106,factory.range(factory.tuple("-106"),factory.tuple("-106")));
        bounds.boundExactly(-105,factory.range(factory.tuple("-105"),factory.tuple("-105")));
        bounds.boundExactly(-104,factory.range(factory.tuple("-104"),factory.tuple("-104")));
        bounds.boundExactly(-103,factory.range(factory.tuple("-103"),factory.tuple("-103")));
        bounds.boundExactly(-102,factory.range(factory.tuple("-102"),factory.tuple("-102")));
        bounds.boundExactly(-101,factory.range(factory.tuple("-101"),factory.tuple("-101")));
        bounds.boundExactly(-100,factory.range(factory.tuple("-100"),factory.tuple("-100")));
        bounds.boundExactly(-99,factory.range(factory.tuple("-99"),factory.tuple("-99")));
        bounds.boundExactly(-98,factory.range(factory.tuple("-98"),factory.tuple("-98")));
        bounds.boundExactly(-97,factory.range(factory.tuple("-97"),factory.tuple("-97")));
        bounds.boundExactly(-96,factory.range(factory.tuple("-96"),factory.tuple("-96")));
        bounds.boundExactly(-95,factory.range(factory.tuple("-95"),factory.tuple("-95")));
        bounds.boundExactly(-94,factory.range(factory.tuple("-94"),factory.tuple("-94")));
        bounds.boundExactly(-93,factory.range(factory.tuple("-93"),factory.tuple("-93")));
        bounds.boundExactly(-92,factory.range(factory.tuple("-92"),factory.tuple("-92")));
        bounds.boundExactly(-91,factory.range(factory.tuple("-91"),factory.tuple("-91")));
        bounds.boundExactly(-90,factory.range(factory.tuple("-90"),factory.tuple("-90")));
        bounds.boundExactly(-89,factory.range(factory.tuple("-89"),factory.tuple("-89")));
        bounds.boundExactly(-88,factory.range(factory.tuple("-88"),factory.tuple("-88")));
        bounds.boundExactly(-87,factory.range(factory.tuple("-87"),factory.tuple("-87")));
        bounds.boundExactly(-86,factory.range(factory.tuple("-86"),factory.tuple("-86")));
        bounds.boundExactly(-85,factory.range(factory.tuple("-85"),factory.tuple("-85")));
        bounds.boundExactly(-84,factory.range(factory.tuple("-84"),factory.tuple("-84")));
        bounds.boundExactly(-83,factory.range(factory.tuple("-83"),factory.tuple("-83")));
        bounds.boundExactly(-82,factory.range(factory.tuple("-82"),factory.tuple("-82")));
        bounds.boundExactly(-81,factory.range(factory.tuple("-81"),factory.tuple("-81")));
        bounds.boundExactly(-80,factory.range(factory.tuple("-80"),factory.tuple("-80")));
        bounds.boundExactly(-79,factory.range(factory.tuple("-79"),factory.tuple("-79")));
        bounds.boundExactly(-78,factory.range(factory.tuple("-78"),factory.tuple("-78")));
        bounds.boundExactly(-77,factory.range(factory.tuple("-77"),factory.tuple("-77")));
        bounds.boundExactly(-76,factory.range(factory.tuple("-76"),factory.tuple("-76")));
        bounds.boundExactly(-75,factory.range(factory.tuple("-75"),factory.tuple("-75")));
        bounds.boundExactly(-74,factory.range(factory.tuple("-74"),factory.tuple("-74")));
        bounds.boundExactly(-73,factory.range(factory.tuple("-73"),factory.tuple("-73")));
        bounds.boundExactly(-72,factory.range(factory.tuple("-72"),factory.tuple("-72")));
        bounds.boundExactly(-71,factory.range(factory.tuple("-71"),factory.tuple("-71")));
        bounds.boundExactly(-70,factory.range(factory.tuple("-70"),factory.tuple("-70")));
        bounds.boundExactly(-69,factory.range(factory.tuple("-69"),factory.tuple("-69")));
        bounds.boundExactly(-68,factory.range(factory.tuple("-68"),factory.tuple("-68")));
        bounds.boundExactly(-67,factory.range(factory.tuple("-67"),factory.tuple("-67")));
        bounds.boundExactly(-66,factory.range(factory.tuple("-66"),factory.tuple("-66")));
        bounds.boundExactly(-65,factory.range(factory.tuple("-65"),factory.tuple("-65")));
        bounds.boundExactly(-64,factory.range(factory.tuple("-64"),factory.tuple("-64")));
        bounds.boundExactly(-63,factory.range(factory.tuple("-63"),factory.tuple("-63")));
        bounds.boundExactly(-62,factory.range(factory.tuple("-62"),factory.tuple("-62")));
        bounds.boundExactly(-61,factory.range(factory.tuple("-61"),factory.tuple("-61")));
        bounds.boundExactly(-60,factory.range(factory.tuple("-60"),factory.tuple("-60")));
        bounds.boundExactly(-59,factory.range(factory.tuple("-59"),factory.tuple("-59")));
        bounds.boundExactly(-58,factory.range(factory.tuple("-58"),factory.tuple("-58")));
        bounds.boundExactly(-57,factory.range(factory.tuple("-57"),factory.tuple("-57")));
        bounds.boundExactly(-56,factory.range(factory.tuple("-56"),factory.tuple("-56")));
        bounds.boundExactly(-55,factory.range(factory.tuple("-55"),factory.tuple("-55")));
        bounds.boundExactly(-54,factory.range(factory.tuple("-54"),factory.tuple("-54")));
        bounds.boundExactly(-53,factory.range(factory.tuple("-53"),factory.tuple("-53")));
        bounds.boundExactly(-52,factory.range(factory.tuple("-52"),factory.tuple("-52")));
        bounds.boundExactly(-51,factory.range(factory.tuple("-51"),factory.tuple("-51")));
        bounds.boundExactly(-50,factory.range(factory.tuple("-50"),factory.tuple("-50")));
        bounds.boundExactly(-49,factory.range(factory.tuple("-49"),factory.tuple("-49")));
        bounds.boundExactly(-48,factory.range(factory.tuple("-48"),factory.tuple("-48")));
        bounds.boundExactly(-47,factory.range(factory.tuple("-47"),factory.tuple("-47")));
        bounds.boundExactly(-46,factory.range(factory.tuple("-46"),factory.tuple("-46")));
        bounds.boundExactly(-45,factory.range(factory.tuple("-45"),factory.tuple("-45")));
        bounds.boundExactly(-44,factory.range(factory.tuple("-44"),factory.tuple("-44")));
        bounds.boundExactly(-43,factory.range(factory.tuple("-43"),factory.tuple("-43")));
        bounds.boundExactly(-42,factory.range(factory.tuple("-42"),factory.tuple("-42")));
        bounds.boundExactly(-41,factory.range(factory.tuple("-41"),factory.tuple("-41")));
        bounds.boundExactly(-40,factory.range(factory.tuple("-40"),factory.tuple("-40")));
        bounds.boundExactly(-39,factory.range(factory.tuple("-39"),factory.tuple("-39")));
        bounds.boundExactly(-38,factory.range(factory.tuple("-38"),factory.tuple("-38")));
        bounds.boundExactly(-37,factory.range(factory.tuple("-37"),factory.tuple("-37")));
        bounds.boundExactly(-36,factory.range(factory.tuple("-36"),factory.tuple("-36")));
        bounds.boundExactly(-35,factory.range(factory.tuple("-35"),factory.tuple("-35")));
        bounds.boundExactly(-34,factory.range(factory.tuple("-34"),factory.tuple("-34")));
        bounds.boundExactly(-33,factory.range(factory.tuple("-33"),factory.tuple("-33")));
        bounds.boundExactly(-32,factory.range(factory.tuple("-32"),factory.tuple("-32")));
        bounds.boundExactly(-31,factory.range(factory.tuple("-31"),factory.tuple("-31")));
        bounds.boundExactly(-30,factory.range(factory.tuple("-30"),factory.tuple("-30")));
        bounds.boundExactly(-29,factory.range(factory.tuple("-29"),factory.tuple("-29")));
        bounds.boundExactly(-28,factory.range(factory.tuple("-28"),factory.tuple("-28")));
        bounds.boundExactly(-27,factory.range(factory.tuple("-27"),factory.tuple("-27")));
        bounds.boundExactly(-26,factory.range(factory.tuple("-26"),factory.tuple("-26")));
        bounds.boundExactly(-25,factory.range(factory.tuple("-25"),factory.tuple("-25")));
        bounds.boundExactly(-24,factory.range(factory.tuple("-24"),factory.tuple("-24")));
        bounds.boundExactly(-23,factory.range(factory.tuple("-23"),factory.tuple("-23")));
        bounds.boundExactly(-22,factory.range(factory.tuple("-22"),factory.tuple("-22")));
        bounds.boundExactly(-21,factory.range(factory.tuple("-21"),factory.tuple("-21")));
        bounds.boundExactly(-20,factory.range(factory.tuple("-20"),factory.tuple("-20")));
        bounds.boundExactly(-19,factory.range(factory.tuple("-19"),factory.tuple("-19")));
        bounds.boundExactly(-18,factory.range(factory.tuple("-18"),factory.tuple("-18")));
        bounds.boundExactly(-17,factory.range(factory.tuple("-17"),factory.tuple("-17")));
        bounds.boundExactly(-16,factory.range(factory.tuple("-16"),factory.tuple("-16")));
        bounds.boundExactly(-15,factory.range(factory.tuple("-15"),factory.tuple("-15")));
        bounds.boundExactly(-14,factory.range(factory.tuple("-14"),factory.tuple("-14")));
        bounds.boundExactly(-13,factory.range(factory.tuple("-13"),factory.tuple("-13")));
        bounds.boundExactly(-12,factory.range(factory.tuple("-12"),factory.tuple("-12")));
        bounds.boundExactly(-11,factory.range(factory.tuple("-11"),factory.tuple("-11")));
        bounds.boundExactly(-10,factory.range(factory.tuple("-10"),factory.tuple("-10")));
        bounds.boundExactly(-9,factory.range(factory.tuple("-9"),factory.tuple("-9")));
        bounds.boundExactly(-8,factory.range(factory.tuple("-8"),factory.tuple("-8")));
        bounds.boundExactly(-7,factory.range(factory.tuple("-7"),factory.tuple("-7")));
        bounds.boundExactly(-6,factory.range(factory.tuple("-6"),factory.tuple("-6")));
        bounds.boundExactly(-5,factory.range(factory.tuple("-5"),factory.tuple("-5")));
        bounds.boundExactly(-4,factory.range(factory.tuple("-4"),factory.tuple("-4")));
        bounds.boundExactly(-3,factory.range(factory.tuple("-3"),factory.tuple("-3")));
        bounds.boundExactly(-2,factory.range(factory.tuple("-2"),factory.tuple("-2")));
        bounds.boundExactly(-1,factory.range(factory.tuple("-1"),factory.tuple("-1")));
        bounds.boundExactly(0,factory.range(factory.tuple("0"),factory.tuple("0")));
        bounds.boundExactly(1,factory.range(factory.tuple("1"),factory.tuple("1")));
        bounds.boundExactly(2,factory.range(factory.tuple("2"),factory.tuple("2")));
        bounds.boundExactly(3,factory.range(factory.tuple("3"),factory.tuple("3")));
        bounds.boundExactly(4,factory.range(factory.tuple("4"),factory.tuple("4")));
        bounds.boundExactly(5,factory.range(factory.tuple("5"),factory.tuple("5")));
        bounds.boundExactly(6,factory.range(factory.tuple("6"),factory.tuple("6")));
        bounds.boundExactly(7,factory.range(factory.tuple("7"),factory.tuple("7")));
        bounds.boundExactly(8,factory.range(factory.tuple("8"),factory.tuple("8")));
        bounds.boundExactly(9,factory.range(factory.tuple("9"),factory.tuple("9")));
        bounds.boundExactly(10,factory.range(factory.tuple("10"),factory.tuple("10")));
        bounds.boundExactly(11,factory.range(factory.tuple("11"),factory.tuple("11")));
        bounds.boundExactly(12,factory.range(factory.tuple("12"),factory.tuple("12")));
        bounds.boundExactly(13,factory.range(factory.tuple("13"),factory.tuple("13")));
        bounds.boundExactly(14,factory.range(factory.tuple("14"),factory.tuple("14")));
        bounds.boundExactly(15,factory.range(factory.tuple("15"),factory.tuple("15")));
        bounds.boundExactly(16,factory.range(factory.tuple("16"),factory.tuple("16")));
        bounds.boundExactly(17,factory.range(factory.tuple("17"),factory.tuple("17")));
        bounds.boundExactly(18,factory.range(factory.tuple("18"),factory.tuple("18")));
        bounds.boundExactly(19,factory.range(factory.tuple("19"),factory.tuple("19")));
        bounds.boundExactly(20,factory.range(factory.tuple("20"),factory.tuple("20")));
        bounds.boundExactly(21,factory.range(factory.tuple("21"),factory.tuple("21")));
        bounds.boundExactly(22,factory.range(factory.tuple("22"),factory.tuple("22")));
        bounds.boundExactly(23,factory.range(factory.tuple("23"),factory.tuple("23")));
        bounds.boundExactly(24,factory.range(factory.tuple("24"),factory.tuple("24")));
        bounds.boundExactly(25,factory.range(factory.tuple("25"),factory.tuple("25")));
        bounds.boundExactly(26,factory.range(factory.tuple("26"),factory.tuple("26")));
        bounds.boundExactly(27,factory.range(factory.tuple("27"),factory.tuple("27")));
        bounds.boundExactly(28,factory.range(factory.tuple("28"),factory.tuple("28")));
        bounds.boundExactly(29,factory.range(factory.tuple("29"),factory.tuple("29")));
        bounds.boundExactly(30,factory.range(factory.tuple("30"),factory.tuple("30")));
        bounds.boundExactly(31,factory.range(factory.tuple("31"),factory.tuple("31")));
        bounds.boundExactly(32,factory.range(factory.tuple("32"),factory.tuple("32")));
        bounds.boundExactly(33,factory.range(factory.tuple("33"),factory.tuple("33")));
        bounds.boundExactly(34,factory.range(factory.tuple("34"),factory.tuple("34")));
        bounds.boundExactly(35,factory.range(factory.tuple("35"),factory.tuple("35")));
        bounds.boundExactly(36,factory.range(factory.tuple("36"),factory.tuple("36")));
        bounds.boundExactly(37,factory.range(factory.tuple("37"),factory.tuple("37")));
        bounds.boundExactly(38,factory.range(factory.tuple("38"),factory.tuple("38")));
        bounds.boundExactly(39,factory.range(factory.tuple("39"),factory.tuple("39")));
        bounds.boundExactly(40,factory.range(factory.tuple("40"),factory.tuple("40")));
        bounds.boundExactly(41,factory.range(factory.tuple("41"),factory.tuple("41")));
        bounds.boundExactly(42,factory.range(factory.tuple("42"),factory.tuple("42")));
        bounds.boundExactly(43,factory.range(factory.tuple("43"),factory.tuple("43")));
        bounds.boundExactly(44,factory.range(factory.tuple("44"),factory.tuple("44")));
        bounds.boundExactly(45,factory.range(factory.tuple("45"),factory.tuple("45")));
        bounds.boundExactly(46,factory.range(factory.tuple("46"),factory.tuple("46")));
        bounds.boundExactly(47,factory.range(factory.tuple("47"),factory.tuple("47")));
        bounds.boundExactly(48,factory.range(factory.tuple("48"),factory.tuple("48")));
        bounds.boundExactly(49,factory.range(factory.tuple("49"),factory.tuple("49")));
        bounds.boundExactly(50,factory.range(factory.tuple("50"),factory.tuple("50")));
        bounds.boundExactly(51,factory.range(factory.tuple("51"),factory.tuple("51")));
        bounds.boundExactly(52,factory.range(factory.tuple("52"),factory.tuple("52")));
        bounds.boundExactly(53,factory.range(factory.tuple("53"),factory.tuple("53")));
        bounds.boundExactly(54,factory.range(factory.tuple("54"),factory.tuple("54")));
        bounds.boundExactly(55,factory.range(factory.tuple("55"),factory.tuple("55")));
        bounds.boundExactly(56,factory.range(factory.tuple("56"),factory.tuple("56")));
        bounds.boundExactly(57,factory.range(factory.tuple("57"),factory.tuple("57")));
        bounds.boundExactly(58,factory.range(factory.tuple("58"),factory.tuple("58")));
        bounds.boundExactly(59,factory.range(factory.tuple("59"),factory.tuple("59")));
        bounds.boundExactly(60,factory.range(factory.tuple("60"),factory.tuple("60")));
        bounds.boundExactly(61,factory.range(factory.tuple("61"),factory.tuple("61")));
        bounds.boundExactly(62,factory.range(factory.tuple("62"),factory.tuple("62")));
        bounds.boundExactly(63,factory.range(factory.tuple("63"),factory.tuple("63")));
        bounds.boundExactly(64,factory.range(factory.tuple("64"),factory.tuple("64")));
        bounds.boundExactly(65,factory.range(factory.tuple("65"),factory.tuple("65")));
        bounds.boundExactly(66,factory.range(factory.tuple("66"),factory.tuple("66")));
        bounds.boundExactly(67,factory.range(factory.tuple("67"),factory.tuple("67")));
        bounds.boundExactly(68,factory.range(factory.tuple("68"),factory.tuple("68")));
        bounds.boundExactly(69,factory.range(factory.tuple("69"),factory.tuple("69")));
        bounds.boundExactly(70,factory.range(factory.tuple("70"),factory.tuple("70")));
        bounds.boundExactly(71,factory.range(factory.tuple("71"),factory.tuple("71")));
        bounds.boundExactly(72,factory.range(factory.tuple("72"),factory.tuple("72")));
        bounds.boundExactly(73,factory.range(factory.tuple("73"),factory.tuple("73")));
        bounds.boundExactly(74,factory.range(factory.tuple("74"),factory.tuple("74")));
        bounds.boundExactly(75,factory.range(factory.tuple("75"),factory.tuple("75")));
        bounds.boundExactly(76,factory.range(factory.tuple("76"),factory.tuple("76")));
        bounds.boundExactly(77,factory.range(factory.tuple("77"),factory.tuple("77")));
        bounds.boundExactly(78,factory.range(factory.tuple("78"),factory.tuple("78")));
        bounds.boundExactly(79,factory.range(factory.tuple("79"),factory.tuple("79")));
        bounds.boundExactly(80,factory.range(factory.tuple("80"),factory.tuple("80")));
        bounds.boundExactly(81,factory.range(factory.tuple("81"),factory.tuple("81")));
        bounds.boundExactly(82,factory.range(factory.tuple("82"),factory.tuple("82")));
        bounds.boundExactly(83,factory.range(factory.tuple("83"),factory.tuple("83")));
        bounds.boundExactly(84,factory.range(factory.tuple("84"),factory.tuple("84")));
        bounds.boundExactly(85,factory.range(factory.tuple("85"),factory.tuple("85")));
        bounds.boundExactly(86,factory.range(factory.tuple("86"),factory.tuple("86")));
        bounds.boundExactly(87,factory.range(factory.tuple("87"),factory.tuple("87")));
        bounds.boundExactly(88,factory.range(factory.tuple("88"),factory.tuple("88")));
        bounds.boundExactly(89,factory.range(factory.tuple("89"),factory.tuple("89")));
        bounds.boundExactly(90,factory.range(factory.tuple("90"),factory.tuple("90")));
        bounds.boundExactly(91,factory.range(factory.tuple("91"),factory.tuple("91")));
        bounds.boundExactly(92,factory.range(factory.tuple("92"),factory.tuple("92")));
        bounds.boundExactly(93,factory.range(factory.tuple("93"),factory.tuple("93")));
        bounds.boundExactly(94,factory.range(factory.tuple("94"),factory.tuple("94")));
        bounds.boundExactly(95,factory.range(factory.tuple("95"),factory.tuple("95")));
        bounds.boundExactly(96,factory.range(factory.tuple("96"),factory.tuple("96")));
        bounds.boundExactly(97,factory.range(factory.tuple("97"),factory.tuple("97")));
        bounds.boundExactly(98,factory.range(factory.tuple("98"),factory.tuple("98")));
        bounds.boundExactly(99,factory.range(factory.tuple("99"),factory.tuple("99")));
        bounds.boundExactly(100,factory.range(factory.tuple("100"),factory.tuple("100")));
        bounds.boundExactly(101,factory.range(factory.tuple("101"),factory.tuple("101")));
        bounds.boundExactly(102,factory.range(factory.tuple("102"),factory.tuple("102")));
        bounds.boundExactly(103,factory.range(factory.tuple("103"),factory.tuple("103")));
        bounds.boundExactly(104,factory.range(factory.tuple("104"),factory.tuple("104")));
        bounds.boundExactly(105,factory.range(factory.tuple("105"),factory.tuple("105")));
        bounds.boundExactly(106,factory.range(factory.tuple("106"),factory.tuple("106")));
        bounds.boundExactly(107,factory.range(factory.tuple("107"),factory.tuple("107")));
        bounds.boundExactly(108,factory.range(factory.tuple("108"),factory.tuple("108")));
        bounds.boundExactly(109,factory.range(factory.tuple("109"),factory.tuple("109")));
        bounds.boundExactly(110,factory.range(factory.tuple("110"),factory.tuple("110")));
        bounds.boundExactly(111,factory.range(factory.tuple("111"),factory.tuple("111")));
        bounds.boundExactly(112,factory.range(factory.tuple("112"),factory.tuple("112")));
        bounds.boundExactly(113,factory.range(factory.tuple("113"),factory.tuple("113")));
        bounds.boundExactly(114,factory.range(factory.tuple("114"),factory.tuple("114")));
        bounds.boundExactly(115,factory.range(factory.tuple("115"),factory.tuple("115")));
        bounds.boundExactly(116,factory.range(factory.tuple("116"),factory.tuple("116")));
        bounds.boundExactly(117,factory.range(factory.tuple("117"),factory.tuple("117")));
        bounds.boundExactly(118,factory.range(factory.tuple("118"),factory.tuple("118")));
        bounds.boundExactly(119,factory.range(factory.tuple("119"),factory.tuple("119")));
        bounds.boundExactly(120,factory.range(factory.tuple("120"),factory.tuple("120")));
        bounds.boundExactly(121,factory.range(factory.tuple("121"),factory.tuple("121")));
        bounds.boundExactly(122,factory.range(factory.tuple("122"),factory.tuple("122")));
        bounds.boundExactly(123,factory.range(factory.tuple("123"),factory.tuple("123")));
        bounds.boundExactly(124,factory.range(factory.tuple("124"),factory.tuple("124")));
        bounds.boundExactly(125,factory.range(factory.tuple("125"),factory.tuple("125")));
        bounds.boundExactly(126,factory.range(factory.tuple("126"),factory.tuple("126")));
        bounds.boundExactly(127,factory.range(factory.tuple("127"),factory.tuple("127")));

        // Add constant symbols
        for(String a: atomlist) {
            Relation ra = Relation.unary(a);
            bounds.boundExactly(ra, factory.setOf(factory.tuple(a)));
        }

        return bounds;
    }
    @Override
    public Formula verifyformula() {
        Expression x21=x9.intersection(x10);
        Formula x20=x21.no();
        Expression x25=x6.product(x11);
        Expression x24=x6.join(x25);
        Formula x23=x24.one();
        Formula x26=x24.in(Expression.INTS);
        Formula x22=x23.and(x26);
        Expression x31=x6.product(x12);
        Expression x30=x6.join(x31);
        Formula x29=x30.one();
        Formula x32=x30.in(x7);
        Formula x28=x29.and(x32);
        Expression x36=x6.product(x13);
        Expression x35=x6.join(x36);
        Formula x34=x35.one();
        Formula x37=x35.in(x7);
        Formula x33=x34.and(x37);
        Variable x40=Variable.unary("synth_this");
        Decls x39=x40.oneOf(x7);
        Expression x43=x40.join(x14);
        Formula x42=x43.one();
        Formula x44=x43.in(Expression.INTS);
        Formula x41=x42.and(x44);
        Formula x38=x41.forAll(x39);
        Expression x46=x14.join(Expression.UNIV);
        Formula x45=x46.in(x7);
        Variable x50=Variable.unary("synth_this");
        Decls x49=x50.oneOf(x7);
        Expression x53=x50.join(x15);
        Formula x52=x53.one();
        Expression x55=x9.union(x10);
        Formula x54=x53.in(x55);
        Formula x51=x52.and(x54);
        Formula x48=x51.forAll(x49);
        Expression x57=x15.join(Expression.UNIV);
        Formula x56=x57.in(x7);
        Expression x60=x8.product(x16);
        Expression x59=x8.join(x60);
        Formula x58=x59.in(x7);
        Expression x63=x8.product(x17);
        Expression x62=x8.join(x63);
        Expression x64=x7.product(x7);
        Formula x61=x62.in(x64);
        Formula x65=x17.totalOrder(x7,x16,x18);
        Variable x68=Variable.unary("synthformula_c");
        Decls x67=x68.oneOf(x6);
        Expression x72=x68.join(x25);
        Formula x71=x72.one();
        Expression x76=x68.join(x31);
        Formula x75=x76.one();
        Expression x81=x68.join(x31);
        Formula x80=x81.eq(x16);
        Formula x79=x80.not();
        Expression x84=x17.closure();
        Expression x83=x12.join(x84);
        Formula x82=x13.in(x83);
        Formula x78=x79.and(x82);
        Expression x88=x17.join(x7);
        Expression x87=x7.difference(x88);
        Formula x86=x13.eq(x87);
        Formula x85=x86.not();
        Formula x77=x78.and(x85);
        Formula x74=x75.and(x77);
        Expression x93=x16.join(x14);
        IntExpression x92=x93.sum();
        IntExpression x94=IntConstant.constant(66);
        Formula x91=x92.eq(x94);
        Expression x97=x13.join(x14);
        IntExpression x96=x97.sum();
        Expression x99=x87.join(x14);
        IntExpression x98=x99.sum();
        Formula x95=x96.eq(x98);
        Formula x90=x91.and(x95);
        Expression x101=x13.join(x15);
        Expression x102=x87.join(x15);
        Formula x100=x101.eq(x102);
        Formula x89=x90.and(x100);
        Formula x73=x74.and(x89);
        Formula x70=x71.and(x73);
        Expression x106=x68.join(x36);
        Formula x105=x106.one();
        Expression x108=x16.join(x15);
        Formula x107=x108.eq(x10);
        Formula x104=x105.and(x107);
        Expression x112=x12.join(x14);
        IntExpression x111=x112.sum();
        IntExpression x113=IntConstant.constant(75);
        Formula x110=x111.lte(x113);
        Expression x116=x12.join(x14);
        IntExpression x115=x116.sum();
        IntExpression x117=IntConstant.constant(70);
        Formula x114=x115.gte(x117);
        Formula x109=x110.and(x114);
        Formula x103=x104.and(x109);
        Formula x69=x70.and(x103);
        x66=x69.forAll(x67);
        x120=Variable.unary("validsystem_t");
        Decls x119=x120.oneOf(x7);
        Expression x124=x120.join(x14);
        Formula x123=x124.one();
        Expression x126=x120.join(x15);
        Formula x125=x126.one();
        Formula x122=x123.and(x125);
        Formula x130=x120.eq(x87);
        Formula x129=x130.not();
        Formula x128=x129.not();
        Expression x134=x120.join(x15);
        Formula x133=x134.eq(x9);
        Expression x139=x120.join(x14);
        IntExpression x138=x139.sum();
        IntExpression x140=x11.sum();
        Formula x137=x138.lt(x140);
        Expression x144=x120.join(x17);
        Expression x143=x144.join(x15);
        Formula x142=x143.eq(x9);
        Expression x147=x120.join(x17);
        Expression x146=x147.join(x14);
        Expression x151=x120.join(x14);
        IntExpression x150=x151.sum();
        IntExpression x152=IntConstant.constant(1);
        IntExpression x149=x150.plus(x152);
        Expression x148=x149.toExpression();
        Formula x145=x146.eq(x148);
        Formula x141=x142.and(x145);
        Formula x136=x137.implies(x141);
        Formula x154=x137.not();
        Expression x158=x120.join(x17);
        Expression x157=x158.join(x15);
        Formula x156=x157.eq(x10);
        Expression x161=x120.join(x17);
        Expression x160=x161.join(x14);
        Expression x162=x120.join(x14);
        Formula x159=x160.eq(x162);
        Formula x155=x156.and(x159);
        Formula x153=x154.implies(x155);
        Formula x135=x136.and(x153);
        Formula x132=x133.implies(x135);
        Formula x164=x133.not();
        Expression x169=x120.join(x14);
        IntExpression x168=x169.sum();
        IntExpression x170=x11.sum();
        Formula x167=x168.gte(x170);
        Expression x174=x120.join(x17);
        Expression x173=x174.join(x15);
        Formula x172=x173.eq(x10);
        Expression x177=x120.join(x17);
        Expression x176=x177.join(x14);
        Expression x181=x120.join(x14);
        IntExpression x180=x181.sum();
        IntExpression x182=IntConstant.constant(1);
        IntExpression x179=x180.minus(x182);
        Expression x178=x179.toExpression();
        Formula x175=x176.eq(x178);
        Formula x171=x172.and(x175);
        Formula x166=x167.implies(x171);
        Formula x184=x167.not();
        Expression x188=x120.join(x17);
        Expression x187=x188.join(x15);
        Formula x186=x187.eq(x9);
        Expression x191=x120.join(x17);
        Expression x190=x191.join(x14);
        Expression x192=x120.join(x14);
        Formula x189=x190.eq(x192);
        Formula x185=x186.and(x189);
        Formula x183=x184.implies(x185);
        Formula x165=x166.and(x183);
        Formula x163=x164.implies(x165);
        Formula x131=x132.and(x163);
        Formula x127=x128.or(x131);
        x121=x122.and(x127);
        Formula x118=x121.forAll(x119);
        x195=Variable.unary("FGcomfy_t");
        Decls x194=x195.oneOf(x7);
        Expression x200=x17.closure();
        Expression x199=x12.join(x200);
        Formula x198=x195.in(x199);
        Formula x197=x198.not();
        Expression x204=x195.join(x14);
        IntExpression x203=x204.sum();
        IntExpression x205=IntConstant.constant(75);
        Formula x202=x203.lte(x205);
        Expression x208=x195.join(x14);
        IntExpression x207=x208.sum();
        IntExpression x209=IntConstant.constant(70);
        Formula x206=x207.gte(x209);
        Formula x201=x202.and(x206);
        x196=x197.or(x201);
        Formula x193=x196.forAll(x194);
        Formula x210=x0.eq(x0);
        Formula x211=x1.eq(x1);
        Formula x212=x2.eq(x2);
        Formula x213=x3.eq(x3);
        Formula x214=x4.eq(x4);
        Formula x215=x5.eq(x5);
        Formula x216=x6.eq(x6);
        Formula x217=x7.eq(x7);
        Formula x218=x8.eq(x8);
        Formula x219=x9.eq(x9);
        Formula x220=x10.eq(x10);
        Formula x221=x11.eq(x11);
        Formula x222=x12.eq(x12);
        Formula x223=x13.eq(x13);
        Formula x224=x14.eq(x14);
        Formula x225=x15.eq(x15);
        Formula x226=x16.eq(x16);
        Formula x227=x17.eq(x17);
        Formula x228=x18.eq(x18);
        return Formula.compose(FormulaOperator.AND, x20, x22, x28, x33, x38, x45, x48, x56, x58, x61, x65, x66, x118, x193, x210, x211, x212, x213, x214, x215, x216, x217, x218, x219, x220, x221, x222, x223, x224, x225, x226, x227, x228);
    }

    // CEGIS
    @Override
    public Formula synthformula() {
        // synth for some config
        List<Formula> formulas = new ArrayList<>();
        formulas.add(bounds.findRelByName("this/Config").one());
        formulas.add(x66);
        // TODO universal quantification over config types must be moved to an implication guard
        // cegis chooses loop to be too early, forces uncomfy rising temp to by comfy, unsat (add guard, problem solved)
        //formulas.add(bounds.findRelByName("this/Config.F").eq(bounds.findRelByName("Time$5")));
        //formulas.add(bounds.findRelByName("this/Config.G").eq(bounds.findRelByName("Time$6")));
        return Formula.and(formulas);
    }

    // TN note: there is some code duplication here; I didn't want to clobber existing code in a quick test hack
    @Override
    public Collection<SynthGoal> goals() {
        final List<SynthGoal> results = new ArrayList<>();
        final List<Formula> formulas = new ArrayList<>();
        final Map<Variable, Expression> univars = new HashMap<>();
        // valid system forall t
        univars.put(x120,x7);
        formulas.add(x121);
        results.add(new RoomHeatGoal(univars, Formula.and(formulas)));
        formulas.clear();
        univars.clear();
        // FGcomfy forall t
        univars.put(x195,x7);
        formulas.add(x196);
        results.add(new RoomHeatGoal(univars, Formula.and(formulas)));
        formulas.clear();
        univars.clear();
        //
        return results;
    }

    @Override
    public Bounds restrict(Bounds verifybounds, Instance synth, boolean onlySkeleton) {
        Bounds restricted = verifybounds.clone();
        restricted.boundExactly(verifybounds.findRelByName("this/Config.T"), synth.tuples("this/Config.T"));
        restricted.boundExactly(verifybounds.findRelByName("this/Config.F"), synth.tuples("this/Config.F"));
        restricted.boundExactly(verifybounds.findRelByName("this/Config.G"), synth.tuples("this/Config.G"));
        restricted.boundExactly(verifybounds.findRelByName("this/Time.heat"), synth.tuples("this/Time.heat"));
        restricted.boundExactly(verifybounds.findRelByName("this/Time.temp"), synth.tuples("this/Time.temp"));
        return restricted;
    }
    @Override
    public Bounds refine(Bounds synthbounds, Instance synth, Instance verify)  {
        throw new UnsupportedOperationException();
    }

    // Target-oriented
    @Override
    public Bounds target(Bounds bounds) { throw new UnsupportedOperationException(); }
}

// TODO class same across specs, make the interface an abstract class?
class RoomHeatGoal implements KodkodExample.SynthGoal {
    Map<Variable, Expression> freevars;
    Formula unboundformula;
    Formula boundformula;

    RoomHeatGoal(Map<Variable, Expression> freevars, Formula unboundformula) {
        this.freevars = new HashMap(freevars);
        this.unboundformula = unboundformula;
        this.boundformula = unboundformula;
        for(Variable v : freevars.keySet()) {
            this.boundformula = this.boundformula().forAll(v.oneOf(freevars.get(v)));
        }
    }
    public Map<Variable, Expression> freevars() { return freevars; }
    public Formula unboundformula() { return unboundformula; }
    public Formula boundformula() { return boundformula; }

    public Formula instantiateWithCE(Instance ce, Bounds b) {
        // Need to produce phi(ce).
        Formula f = unboundformula;
        System.out.println("instantiateWithCE: "+freevars);
        for(Variable v : freevars.keySet()) {
            Relation skolemRel = ce.findRelationByName("$"+v);
            TupleSet relTuples = ce.relationTuples().get(skolemRel);
            String constStr = "";
            // TODO: hack! assume that the name of the relation and the name of the atom are the same Java string
            for(Tuple t : relTuples) {
                constStr = t.atom(0).toString();
                break;
            }
            f = f.accept(new SubstituteVisitor(v, b.findRelByName(constStr)));
        }
        return f;
    }

}